[Theme]
Current=RangeOS
FacesDir=/usr/share/sddm/faces
ThemeDir=/usr/share/sddm/themes

[Users]
MaximumUid=60000
MinimumUid=1000
HideUsers=nobody,nobody4,noaccess
RememberLastUser=true
RememberLastSession=false
DefaultSession=rangeos-shell.desktop

[Autologin]
Relogin=false

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot
