# Calamares Settings for RangeOS AI
# Target: Ubuntu Noble Base

modules-search: [ local ]

instances:
- id:       rangeos-branding
  module:   branding
  config:   branding.conf

sequence:
- show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
- exec:
    - partition
    - mount
    - unpackfs
    - sources-yami
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - luksbootkeyfile
    - luksopensslcfg
    - initcpiocfg
    - initcpio
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - bootloader
    - postcfg
    - umount
- show:
    - finished

brand-id: rangeos
show-back-button: true
show-next-button: true
show-cancel-button: true
